/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminProfileRouteImport } from './routes/_admin/profile'
import { Route as AdminOrdersRouteImport } from './routes/_admin/orders'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin-users'
import { Route as AdminProductsIndexRouteImport } from './routes/_admin/products.index'
import { Route as AdminProductsNewRouteImport } from './routes/_admin/products.new'
import { Route as AdminProductsHomePageRouteImport } from './routes/_admin/products.home-page'
import { Route as AdminConfigurationsOfferCategoriesRouteImport } from './routes/_admin/configurations.offer-categories'
import { Route as AdminConfigurationsHomePageSectionsRouteImport } from './routes/_admin/configurations.home-page-sections'
import { Route as AdminConfigurationsCategoriesRouteImport } from './routes/_admin/configurations.categories'
import { Route as AdminConfigurationsBrandsRouteImport } from './routes/_admin/configurations.brands'
import { Route as AdminConfigurationsBannersRouteImport } from './routes/_admin/configurations.banners'
import { Route as AdminProductsProductIdIndexRouteImport } from './routes/_admin/products.$productId.index'
import { Route as AdminProductsProductIdEditRouteImport } from './routes/_admin/products.$productId.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin-users',
  path: '/admin-users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsHomePageRoute = AdminProductsHomePageRouteImport.update({
  id: '/products/home-page',
  path: '/products/home-page',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigurationsOfferCategoriesRoute =
  AdminConfigurationsOfferCategoriesRouteImport.update({
    id: '/configurations/offer-categories',
    path: '/configurations/offer-categories',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminConfigurationsHomePageSectionsRoute =
  AdminConfigurationsHomePageSectionsRouteImport.update({
    id: '/configurations/home-page-sections',
    path: '/configurations/home-page-sections',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminConfigurationsCategoriesRoute =
  AdminConfigurationsCategoriesRouteImport.update({
    id: '/configurations/categories',
    path: '/configurations/categories',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminConfigurationsBrandsRoute =
  AdminConfigurationsBrandsRouteImport.update({
    id: '/configurations/brands',
    path: '/configurations/brands',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminConfigurationsBannersRoute =
  AdminConfigurationsBannersRouteImport.update({
    id: '/configurations/banners',
    path: '/configurations/banners',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminProductsProductIdIndexRoute =
  AdminProductsProductIdIndexRouteImport.update({
    id: '/products/$productId/',
    path: '/products/$productId/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminProductsProductIdEditRoute =
  AdminProductsProductIdEditRouteImport.update({
    id: '/products/$productId/edit',
    path: '/products/$productId/edit',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin-users': typeof AdminAdminUsersRoute
  '/dashboard': typeof AdminDashboardRoute
  '/orders': typeof AdminOrdersRoute
  '/profile': typeof AdminProfileRoute
  '/configurations/banners': typeof AdminConfigurationsBannersRoute
  '/configurations/brands': typeof AdminConfigurationsBrandsRoute
  '/configurations/categories': typeof AdminConfigurationsCategoriesRoute
  '/configurations/home-page-sections': typeof AdminConfigurationsHomePageSectionsRoute
  '/configurations/offer-categories': typeof AdminConfigurationsOfferCategoriesRoute
  '/products/home-page': typeof AdminProductsHomePageRoute
  '/products/new': typeof AdminProductsNewRoute
  '/products/': typeof AdminProductsIndexRoute
  '/products/$productId/edit': typeof AdminProductsProductIdEditRoute
  '/products/$productId/': typeof AdminProductsProductIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin-users': typeof AdminAdminUsersRoute
  '/dashboard': typeof AdminDashboardRoute
  '/orders': typeof AdminOrdersRoute
  '/profile': typeof AdminProfileRoute
  '/configurations/banners': typeof AdminConfigurationsBannersRoute
  '/configurations/brands': typeof AdminConfigurationsBrandsRoute
  '/configurations/categories': typeof AdminConfigurationsCategoriesRoute
  '/configurations/home-page-sections': typeof AdminConfigurationsHomePageSectionsRoute
  '/configurations/offer-categories': typeof AdminConfigurationsOfferCategoriesRoute
  '/products/home-page': typeof AdminProductsHomePageRoute
  '/products/new': typeof AdminProductsNewRoute
  '/products': typeof AdminProductsIndexRoute
  '/products/$productId/edit': typeof AdminProductsProductIdEditRoute
  '/products/$productId': typeof AdminProductsProductIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/admin-users': typeof AdminAdminUsersRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/orders': typeof AdminOrdersRoute
  '/_admin/profile': typeof AdminProfileRoute
  '/_admin/configurations/banners': typeof AdminConfigurationsBannersRoute
  '/_admin/configurations/brands': typeof AdminConfigurationsBrandsRoute
  '/_admin/configurations/categories': typeof AdminConfigurationsCategoriesRoute
  '/_admin/configurations/home-page-sections': typeof AdminConfigurationsHomePageSectionsRoute
  '/_admin/configurations/offer-categories': typeof AdminConfigurationsOfferCategoriesRoute
  '/_admin/products/home-page': typeof AdminProductsHomePageRoute
  '/_admin/products/new': typeof AdminProductsNewRoute
  '/_admin/products/': typeof AdminProductsIndexRoute
  '/_admin/products/$productId/edit': typeof AdminProductsProductIdEditRoute
  '/_admin/products/$productId/': typeof AdminProductsProductIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin-users'
    | '/dashboard'
    | '/orders'
    | '/profile'
    | '/configurations/banners'
    | '/configurations/brands'
    | '/configurations/categories'
    | '/configurations/home-page-sections'
    | '/configurations/offer-categories'
    | '/products/home-page'
    | '/products/new'
    | '/products/'
    | '/products/$productId/edit'
    | '/products/$productId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin-users'
    | '/dashboard'
    | '/orders'
    | '/profile'
    | '/configurations/banners'
    | '/configurations/brands'
    | '/configurations/categories'
    | '/configurations/home-page-sections'
    | '/configurations/offer-categories'
    | '/products/home-page'
    | '/products/new'
    | '/products'
    | '/products/$productId/edit'
    | '/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/_admin/admin-users'
    | '/_admin/dashboard'
    | '/_admin/orders'
    | '/_admin/profile'
    | '/_admin/configurations/banners'
    | '/_admin/configurations/brands'
    | '/_admin/configurations/categories'
    | '/_admin/configurations/home-page-sections'
    | '/_admin/configurations/offer-categories'
    | '/_admin/products/home-page'
    | '/_admin/products/new'
    | '/_admin/products/'
    | '/_admin/products/$productId/edit'
    | '/_admin/products/$productId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/profile': {
      id: '/_admin/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/orders': {
      id: '/_admin/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin-users': {
      id: '/_admin/admin-users'
      path: '/admin-users'
      fullPath: '/admin-users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/products/': {
      id: '/_admin/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/products/new': {
      id: '/_admin/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/products/home-page': {
      id: '/_admin/products/home-page'
      path: '/products/home-page'
      fullPath: '/products/home-page'
      preLoaderRoute: typeof AdminProductsHomePageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/configurations/offer-categories': {
      id: '/_admin/configurations/offer-categories'
      path: '/configurations/offer-categories'
      fullPath: '/configurations/offer-categories'
      preLoaderRoute: typeof AdminConfigurationsOfferCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/configurations/home-page-sections': {
      id: '/_admin/configurations/home-page-sections'
      path: '/configurations/home-page-sections'
      fullPath: '/configurations/home-page-sections'
      preLoaderRoute: typeof AdminConfigurationsHomePageSectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/configurations/categories': {
      id: '/_admin/configurations/categories'
      path: '/configurations/categories'
      fullPath: '/configurations/categories'
      preLoaderRoute: typeof AdminConfigurationsCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/configurations/brands': {
      id: '/_admin/configurations/brands'
      path: '/configurations/brands'
      fullPath: '/configurations/brands'
      preLoaderRoute: typeof AdminConfigurationsBrandsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/configurations/banners': {
      id: '/_admin/configurations/banners'
      path: '/configurations/banners'
      fullPath: '/configurations/banners'
      preLoaderRoute: typeof AdminConfigurationsBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/products/$productId/': {
      id: '/_admin/products/$productId/'
      path: '/products/$productId'
      fullPath: '/products/$productId/'
      preLoaderRoute: typeof AdminProductsProductIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/products/$productId/edit': {
      id: '/_admin/products/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/products/$productId/edit'
      preLoaderRoute: typeof AdminProductsProductIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminConfigurationsBannersRoute: typeof AdminConfigurationsBannersRoute
  AdminConfigurationsBrandsRoute: typeof AdminConfigurationsBrandsRoute
  AdminConfigurationsCategoriesRoute: typeof AdminConfigurationsCategoriesRoute
  AdminConfigurationsHomePageSectionsRoute: typeof AdminConfigurationsHomePageSectionsRoute
  AdminConfigurationsOfferCategoriesRoute: typeof AdminConfigurationsOfferCategoriesRoute
  AdminProductsHomePageRoute: typeof AdminProductsHomePageRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminProductsProductIdEditRoute: typeof AdminProductsProductIdEditRoute
  AdminProductsProductIdIndexRoute: typeof AdminProductsProductIdIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminConfigurationsBannersRoute: AdminConfigurationsBannersRoute,
  AdminConfigurationsBrandsRoute: AdminConfigurationsBrandsRoute,
  AdminConfigurationsCategoriesRoute: AdminConfigurationsCategoriesRoute,
  AdminConfigurationsHomePageSectionsRoute:
    AdminConfigurationsHomePageSectionsRoute,
  AdminConfigurationsOfferCategoriesRoute:
    AdminConfigurationsOfferCategoriesRoute,
  AdminProductsHomePageRoute: AdminProductsHomePageRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminProductsProductIdEditRoute: AdminProductsProductIdEditRoute,
  AdminProductsProductIdIndexRoute: AdminProductsProductIdIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
